### PR TITLE
Install latest version of mock by default

### PR DESCRIPTION
**Pull request by kostyrev**
As a role's user,
I want it to install the latest available version of software by default
so that I wasn't forced to remove the old package manually and apply the role.

### CODE REVIEW

**Comment by uchida** [comment]
@kostyrevaa thank you for your contribution.
Use explicit version is appropriate and worth to merge.

However, I’m caring about `tags` in your request, `--tags` or `--skip-tags` are applied in a whole playbook and it’s hard to give consistent tag naming rule across ansible roles.
I prefer roles to be neutral with respect to tag naming, so I would like to avoid using tags inside ansible role.

**Comment by kostyrev** [comment]
Hi!
I've removed those tags.

**Comment by uchida** [comment]
Your request has merged, thanks @kostyrevaa.
version 0.1.2, includes this request, is available on ansible galaxy.

**Comment by uchida** [comment]
After merged this pull request, I realised that using `mock_config` instead of `mock_config_init` seems better.
However it may break backward compatibility, so I will release 0.2.0 later (changes only minor version because currently this role in moratorium, 0.x.x, for semantic versioning).

**Pull request merged**
